notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

services:
  - docker

install: true

addons:
  sonarcloud:
    organization: "javaboilerplates"
    token:
      secure: $SONARCLOUD_TOKEN

language: java

jdk:
  - oraclejdk8

install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./mvnw clean package -DskipTests=true
  - bash script/Dockerbuild.sh

deploy:
  provider: script
  script: bash script/Dockerpush.sh
  on:
    branch: master